# MERGE

In [3]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.DataFrame({'ASCII_Num': np.arange(65,71),
                    'char': [chr(i) for i in range(65, 71)]})

df1

,ASCII_Num,char
0,65,A
1,66,B
2,67,C
3,68,D
4,69,E
5,70,F


In [ ]:
df2 = pd.DataFrame({'ASCII_Num': np.arange(71,76),
                    'char': [chr(i) for i in range(71, 76)]})

df2

,ASCII_Num,char
0,71,G
1,72,H
2,73,I
3,74,J
4,75,K


In [ ]:
df3 = pd.DataFrame({'ASCII_Num': np.arange(69,75),
                    'characters': [chr(i) for i in range(69, 75)]})

df3

,ASCII_Num,characters
0,69,E
1,70,F
2,71,G
3,72,H
4,73,I
5,74,J


In [ ]:
df4 = pd.DataFrame({'ASCII_Numbers': np.arange(71,75),
                    'characters': [chr(i) for i in range(71, 75)]})

df4

,ASCII_Numbers,characters
0,71,G
1,72,H
2,73,I
3,74,J


In [ ]:
merged_df = pd.merge(df1, df2, on='ASCII_Num', how='outer')
merged_df

,ASCII_Num,char_x,char_y
0,65,A,NaN
1,66,B,NaN
2,67,C,NaN
3,68,D,NaN
4,69,E,NaN
5,70,F,NaN
6,71,NaN,G
7,72,NaN,H
8,73,NaN,I
9,74,NaN,J


In [ ]:
merged_df = pd.merge(df1, df2, on='ASCII_Num', how='inner')
merged_df

,ASCII_Num,char_x,char_y


In [ ]:
merged_df = pd.merge(df1, df2, on=['ASCII_Num', 'char'], how='outer')
merged_df

,ASCII_Num,char
0,65,A
1,66,B
2,67,C
3,68,D
4,69,E
5,70,F
6,71,G
7,72,H
8,73,I
9,74,J


In [ ]:
merged_df = pd.merge(df1, df2, on=['ASCII_Num', 'char'], how='inner')
merged_df

,ASCII_Num,char


In [ ]:
merged_df = df1.merge(df3, on=['ASCII_Num'], how='outer')
merged_df

,ASCII_Num,char,characters
0,65,A,NaN
1,66,B,NaN
2,67,C,NaN
3,68,D,NaN
4,69,E,E
5,70,F,F
6,71,NaN,G
7,72,NaN,H
8,73,NaN,I
9,74,NaN,J


In [ ]:
merged_df = df1.merge(df3, on=['ASCII_Num'], how='inner')
merged_df

,ASCII_Num,char,characters
0,69,E,E
1,70,F,F


In [ ]:
merged_df = df1.merge(df3, on=['ASCII_Num'], how='left')
merged_df

,ASCII_Num,char,characters
0,65,A,NaN
1,66,B,NaN
2,67,C,NaN
3,68,D,NaN
4,69,E,E
5,70,F,F


In [ ]:
merged_df = df1.merge(df3, on=['ASCII_Num'], how='right')
merged_df

,ASCII_Num,char,characters
0,69,E,E
1,70,F,F
2,71,NaN,G
3,72,NaN,H
4,73,NaN,I
5,74,NaN,J


## Assign

- Assign is used to add the columns in dataframe

In [ ]:
df = pd.DataFrame()
display(df)

lst = [1, 2, 3, 4]

df = df.assign(Col1= lst)
df

""


,Col1
0,1
1,2
2,3
3,4


In [ ]:
df1 = pd.DataFrame()
display(df1)

""


In [ ]:
list1 = np.random.randint(1, 10, 5)
list1

array([4, 3, 4, 3, 1])

In [ ]:
df1 = df1.assign(Col1 = list1)
df1

,Col1
0,4
1,3
2,4
3,3
4,1


In [ ]:
df1['Col2'] = np.zeros(5)
df1

,Col1,Col2
0,4,0.0
1,3,0.0
2,4,0.0
3,3,0.0
4,1,0.0


In [ ]:
df['Col2'] = [5, 6, 7, 8]
df

,Col1,Col3,Col2
0,1,15,5
1,2,16,6
2,3,17,7
3,4,18,8


In [ ]:
df['Col3'] = [15, 16, 17, 18]
df

,Col1,Col3,Col2
0,1,15,5
1,2,16,6
2,3,17,7
3,4,18,8


## Pop

In [ ]:
# It will Pop out the columns

In [ ]:
df.pop('Col2') # Drop
df

,Col1,Col3
0,1,15
1,2,16
2,3,17
3,4,18


## Values

In [ ]:
# It converts DataFrame ---> Matrix Format (Numpy Array)

In [ ]:
df

,Col1,Col2
0,1,5
1,2,6
2,3,7
3,4,8


In [ ]:
np_array = df.values
np_array

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
df['Col4'] = [1, 2, 3, 4]
df.values

array([[1, 5, 1],
       [2, 6, 2],
       [3, 7, 3],
       [4, 8, 4]])

In [ ]:
df1

,Col1,Col2
0,4,0.0
1,3,0.0
2,4,0.0
3,3,0.0
4,1,0.0


In [ ]:
df1.values

array([[4., 0.],
       [3., 0.],
       [4., 0.],
       [3., 0.],
       [1., 0.]])

## Drop_duplicates()
- for dropping the dupicate values

In [4]:
df = pd.DataFrame({'A': [1, 2, 1, 2],
                   'B': [100, 200, 100, 400],
                   'C':[4, 4, 5, 5]})
df

,A,B,C
0,1,100,4
1,2,200,4
2,1,100,5
3,2,400,5


In [6]:
df.drop_duplicates(['C'])

,A,B,C
0,1,100,4
2,1,100,5


In [8]:
df.drop_duplicates(['A'], keep='first')

,A,B,C
0,1,100,4
1,2,200,4


In [ ]:
df.drop_duplicates(['A'], keep='last')

,A,B,C
2,1,300,5
3,2,400,5


In [ ]:
df.drop_duplicates(['A', 'B'], keep='first')

,A,B,C
0,1,100,4
1,2,200,4
3,2,400,5


In [ ]:
df.drop_duplicates(['A', 'B'], keep='last')

,A,B,C
1,2,200,4
2,1,100,5
3,2,400,5


## Duplicated

In [ ]:
df = pd.DataFrame({'A': [1, 2, 1, 2],
                   'B': [100, 200, 100, 400],
                   'C':[4, 4, 4, 5]})
df

,A,B,C
0,1,100,4
1,2,200,4
2,1,100,4
3,2,400,5


In [ ]:
df.duplicated()

,0
0,False
1,False
2,True
3,False


In [ ]:
df[df.duplicated()]

,A,B,C
2,1,100,4


In [ ]:
df[~(df.duplicated())].reset_index(drop=True)

,A,B,C
0,1,100,4
1,2,200,4
2,2,400,5
