## Mathematical Operations on Array

In [1]:
import numpy as np

In [2]:
array = np.array([2, 3, 4, 5, 6, 7, 8, 9])
array

array([2, 3, 4, 5, 6, 7, 8, 9])

- Addition

In [3]:
array + 10

array([12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
[2, 4, 5, 6] + [10] # addition in List is different that array addition

[2, 4, 5, 6, 10]

In [7]:
array = np.array([[2, 3], [7, 9]])
array + 11

array([[13, 14],
       [18, 20]])

In [8]:
array1 = np.array([2, 3, 4, 5])
array2 = np.array([8, 9, 7, 5])

array1 + array2

array([10, 12, 11, 10])

- Substraction

In [9]:
array = np.array([2, 3, 4, 5, 6, 7, 8, 9])
array - 1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
array = np.array([[2, 3], [7, 9]])
array - 11

array([[-9, -8],
       [-4, -2]])

In [11]:
array1 = np.array([2, 3, 4, 5])
array2 = np.array([8, 9, 7, 5])

array1 - array2

array([-6, -6, -3,  0])

- Multiplication

In [12]:
array = np.array([2, 3, 4, 5, 6, 7, 8, 9])
array * 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
array = np.array([[2, 3], [7, 9]])
array * 5

array([[10, 15],
       [35, 45]])

In [14]:
array1 = np.array([2, 3, 4, 5])
array2 = np.array([8, 9, 7, 5])

array1 * array2

array([16, 27, 28, 25])

In [15]:
array = np.array([[2, 3], [7, 9]])

print((array - 2) + (array * 3))

# 0 1 5 7 + 6 9 21 27

[[ 6 10]
 [26 34]]


- Division

In [16]:
array = np.array([2, 3, 4, 5, 6, 7, 8, 9])
array / 2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [17]:
array = np.array([[2, 3], [7, 9]])
array / 2

array([[1. , 1.5],
       [3.5, 4.5]])

In [18]:
array1 = np.array([2, 3, 4, 5])
array2 = np.array([8, 9, 7, 5])

array1 / array2

array([0.25      , 0.33333333, 0.57142857, 1.        ])

- Floor Division

In [19]:
array = np.array([2, 3, 4, 5, 6, 7, 8, 9])
array // 2

array([1, 1, 2, 2, 3, 3, 4, 4])

In [20]:
array = np.array([[2, 3], [7, 9]])
array // 2

array([[1, 1],
       [3, 4]])

In [21]:
array1 = np.array([2, 3, 4, 5])
array2 = np.array([8, 9, 7, 5])

array1 // array2

array([0, 0, 0, 1])

- Remainder

In [ ]:
# 9 / 2 = 4 floor division -- 1 remainder

# 11 / 2 = 5 -- 1 remainder

# 8 / 2 = 4 -- 0 remainder

# 10 / 3 = 3 -- 1 remainder

In [22]:
array = np.array([2, 3, 4, 5, 6, 7, 8, 9])
array % 2

array([0, 1, 0, 1, 0, 1, 0, 1])

In [23]:
array = np.array([[2, 3], [7, 9]])
array % 2

array([[0, 1],
       [1, 1]])

In [24]:
array1 = np.array([2, 3, 4, 5])
array2 = np.array([8, 9, 7, 5])

array1 % array2

array([2, 3, 4, 0])

In [26]:
array1 = np.array([2, 3, 4, 5])
array2 = np.array([8, 9, 7, 5])

np.remainder(array1, array2)

array([2, 3, 4, 0])

- Square

In [27]:
array = np.array([2, 3, 4, 5, 6, 7, 8, 9])
array ** 2

array([ 4,  9, 16, 25, 36, 49, 64, 81])

In [50]:
np.square(array)
np.sqrt(array) # square root

array([[1.41421356, 1.73205081],
       [2.64575131, 3.        ]])

In [31]:
np.power(array, 4)

array([  16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [34]:
pow(array, 3)

array([  8,  27,  64, 125, 216, 343, 512, 729])

In [37]:
array = np.array([[2, 3], [7, 9]])
array ** 2
np.square(array)

array([[ 4,  9],
       [49, 81]])

### Matrix dot product
(dot --> multiplication)

In [ ]:
# for first column

(a1) first row * (a2) first column

(a1) second row * (a2) first column

# for second column

(a1) first row * (a2) second column

(a1) second row * (a2) second column

In [39]:
arr1 = np.array([[3, 4],
                 [5, 5]])

arr2 = np.array([[5, 6],
                 [3, 4]])

3 * 5 + 4 * 3 --- 3 * 6 + 4 * 4
5 * 5 + 5 * 3 --- 5 * 6 + 5 * 4
arr1, arr2

(array([[3, 4],
        [5, 5]]),
 array([[5, 6],
        [3, 4]]))

In [40]:
np.dot(arr1, arr2)

array([[27, 34],
       [40, 50]])

In [46]:
arr1 = np.array([[3, 4],
                 [5, 5],
                 [0, 1]])

arr2 = np.array([[4, 6, 1],
                 [9, 0, 2]])

np.dot(arr1, arr2)

array([[48, 18, 11],
       [65, 30, 15],
       [ 9,  0,  2]])

In [47]:
arr1 = np.array([[3, 4],
                 [5, 5],
                 [0, 1]])

arr2 = np.array([[4, 6],
                 [5, 6]])


np.dot(arr1, arr2)

array([[32, 42],
       [45, 60],
       [ 5,  6]])

In [ ]:
arr1 = np.array([[3, 4],
                 [5, 5]])

arr2 = np.array([[4, 6],
                 [5, 6]])

arr3 = np.array([[0, 0],
                [0, 0]])

step1 = np.dot(arr1, arr2)

step2 = np.dot(step1, arr3)

In [49]:
arr1 = np.array([[3, 4],
                 [5, 5]])

arr2 = np.array([[4, 6],
                 [5, 6]])

arr3 = np.array([[0, 0],
                [0, 0]])


np.dot(arr1, arr2, arr3)

array([[32, 42],
       [45, 60]])