## How to generate Random Number

In [1]:
import numpy as np
import random

In [2]:
# There are multiple functions to create Random Numbers

random.random() #[0-1] use reshape functions to get 2D or 3D array
random.rand() #[0-1]
random.randint() #[low, high, size, dtype]
random.ranf() #[0-1] use reshape functions to get 2D or 3D array
random.randn() # (0,0) may contain negative values


0.17468547163782755

### Random.rand()
- It will generate values between 0-1

In [3]:
nums = np.random.rand(7)
nums

array([0.49269949, 0.02655308, 0.38869855, 0.64097214, 0.79283651,
       0.49813999, 0.2838522 ])

In [57]:
nums = np.random.rand()
nums

0.38151053854663286

In [7]:
nums = np.random.rand(10)
nums

array([0.77114381, 0.69933099, 0.07934131, 0.68379744, 0.33827599,
       0.51790402, 0.67502976, 0.10779329, 0.03063316, 0.00239112])

In [9]:
nums = np.random.rand(4, 5)
nums

array([[0.91782334, 0.50288699, 0.06157311, 0.6621979 , 0.99752386],
       [0.35521008, 0.21941958, 0.19107756, 0.05898865, 0.76445374],
       [0.67444749, 0.71471084, 0.9010613 , 0.59724771, 0.02396479],
       [0.78850847, 0.96899921, 0.29386087, 0.04167463, 0.63127907]])

In [10]:
nums = np.random.rand(5, 10)
nums

array([[0.97436697, 0.30510767, 0.31861532, 0.31021012, 0.73353695,
        0.27347484, 0.23911211, 0.10153482, 0.49304395, 0.0259541 ],
       [0.75963339, 0.21170552, 0.99113296, 0.0972242 , 0.53859083,
        0.68799899, 0.97908281, 0.20130301, 0.80443264, 0.25914287],
       [0.97734622, 0.33625629, 0.17953653, 0.02199011, 0.2876698 ,
        0.99309718, 0.30046516, 0.99458595, 0.16467554, 0.16195844],
       [0.67952638, 0.32374801, 0.05636657, 0.32025199, 0.96593036,
        0.0238294 , 0.76363617, 0.94910123, 0.3198261 , 0.23726327],
       [0.32292614, 0.8764213 , 0.79094599, 0.42054926, 0.17381722,
        0.33100613, 0.61248657, 0.55446745, 0.55472884, 0.57458713]])

### random.random()

In [11]:
random_nums = np.random.random(10)
random_nums

array([0.81009853, 0.73496324, 0.82702516, 0.89181783, 0.51163422,
       0.19789062, 0.44337733, 0.6843634 , 0.89734967, 0.65110474])

In [12]:
random_nums = np.random.random(7)
random_nums

array([0.39624969, 0.75631094, 0.94012499, 0.07518646, 0.32963351,
       0.12093192, 0.77029586])

In [15]:
random_nums = np.random.random(4).reshape(2, 2)
random_nums

array([[0.60544416, 0.09264708],
       [0.36491201, 0.63497483]])

In [18]:
r_nums = np.random.random(12)
r_nums.reshape(3, 2, 2)


array([[[0.41967538, 0.19447232],
        [0.98153847, 0.31711605]],

       [[0.50198327, 0.00884839],
        [0.49579283, 0.02590565]],

       [[0.3600658 , 0.15716155],
        [0.08459268, 0.56508185]]])

## Random.ranf()
- Values between 0-1

In [19]:
np.random.ranf(7)

array([0.12500122, 0.47087231, 0.12160085, 0.0814393 , 0.92393347,
       0.58335866, 0.89162579])

In [21]:
np.random.ranf(12).reshape(6, 2)

array([[0.5704254 , 0.07526835],
       [0.3739452 , 0.62618788],
       [0.75130577, 0.05063244],
       [0.86179718, 0.33062044],
       [0.28349259, 0.81184492],
       [0.62790861, 0.12347728]])

## random.randint()

In [27]:
np.random.randint(1, 20, 15)

array([15, 19,  2,  9, 14,  4,  8, 10,  5,  7, 16,  2, 12, 18,  4])

In [23]:
np.random.randint(1, 20, size = 15, dtype= 'I')

array([12,  3,  5,  7, 19,  2, 12, 15,  6,  6,  3,  9,  9,  2,  2],
      dtype=uint32)

In [29]:
np.random.randint(low=1, high=20, size=15, dtype='I')

array([11,  4, 11, 13,  5, 14,  2, 15, 11, 14,  2, 18,  4, 18,  2],
      dtype=uint32)

## random.randn()
- it will generate the normally distributed numbers around (0, 0) cordinates

In [32]:
np.random.randn(7)

array([ 1.53633865,  0.09963697,  0.42628529,  1.02205391, -0.00172983,
       -1.10723078,  0.27726036])

In [33]:
np.random.randn(5, 4)

array([[-0.37458572,  1.67926282,  0.08009426,  1.20163707],
       [-1.23777718,  0.65255406, -0.19908177,  0.1080058 ],
       [ 1.37968215, -1.70961952, -0.17793388, -0.07483396],
       [-1.20621877, -1.17535104, -0.48357072,  0.94618994],
       [ 0.56213976, -2.65496119, -0.2156727 , -0.74901555]])

## Sort()

In [34]:
ram_num = np.random.randint(low=1, high=20, size=15, dtype='I')
ram_num

array([10, 17,  9, 12,  5, 15, 18,  3, 14, 18, 12, 17, 10,  9, 15],
      dtype=uint32)

- ascending

In [35]:
np.sort(ram_num)

array([ 3,  5,  9,  9, 10, 10, 12, 12, 14, 15, 15, 17, 17, 18, 18],
      dtype=uint32)

In [42]:
num = np.array(sorted(ram_num, reverse=False))
num

array([ 3,  5,  9,  9, 10, 10, 12, 12, 14, 15, 15, 17, 17, 18, 18],
      dtype=uint32)

- descending

In [40]:
np.sort(ram_num)[::-1]

array([18, 18, 17, 17, 15, 15, 14, 12, 12, 10, 10,  9,  9,  5,  3],
      dtype=uint32)

In [41]:
num = np.array(sorted(ram_num, reverse=True))
num

array([18, 18, 17, 17, 15, 15, 14, 12, 12, 10, 10,  9,  9,  5,  3],
      dtype=uint32)

## Sorting of Matrix

In [43]:
np.sort([2, 3, 5, 0], axis=-1) # rows

array([0, 2, 3, 5])

In [47]:
array = np.array([1, 3, 44, 33, 9, 6, 0, 33, 4, 1, 55, 3]).reshape(4, 3)
array

array([[ 1,  3, 44],
       [33,  9,  6],
       [ 0, 33,  4],
       [ 1, 55,  3]])

- Sorting columns wise

In [48]:
array = np.array([1, 3, 44, 33, 9, 6, 0, 33, 4, 1, 55, 3]).reshape(4, 3)
array

array([[ 1,  3, 44],
       [33,  9,  6],
       [ 0, 33,  4],
       [ 1, 55,  3]])

In [49]:
np.sort(array, axis=1)

array([[ 1,  3, 44],
       [ 6,  9, 33],
       [ 0,  4, 33],
       [ 1,  3, 55]])

In [53]:
ary = np.array([22, 2, 33, 3, 44, 4]).reshape(2, 3)
ary

array([[22,  2, 33],
       [ 3, 44,  4]])

In [54]:
np.sort(ary, axis=1)

array([[ 2, 22, 33],
       [ 3,  4, 44]])

- Sorting raw wise

In [50]:
array = np.array([1, 3, 44, 33, 9, 6, 0, 33, 4, 1, 55, 3]).reshape(4, 3)
array

array([[ 1,  3, 44],
       [33,  9,  6],
       [ 0, 33,  4],
       [ 1, 55,  3]])

In [51]:
np.sort(array, axis=0)

array([[ 0,  3,  3],
       [ 1,  9,  4],
       [ 1, 33,  6],
       [33, 55, 44]])

In [55]:
ary = np.array([22, 2, 33, 3, 44, 4]).reshape(2, 3)
ary

array([[22,  2, 33],
       [ 3, 44,  4]])

In [56]:
np.sort(ary, axis=0)

array([[ 3,  2,  4],
       [22, 44, 33]])