## ceil

In [5]:
# It will yeild out the maximum closest whole number to that decimal number

In [1]:
import numpy as np

In [2]:
a = 2.78
np.ceil(a)

np.float64(3.0)

In [4]:
b = 9.01

np.ceil(b)

np.float64(10.0)

In [6]:
c = 11.45
np.ceil(c)

np.float64(12.0)

In [17]:
np.ceil(11.5)

np.float64(12.0)

## Floor

In [8]:
# It will give minimum closest value of a whole number

In [7]:
a = 4.56
np.floor(a)

np.float64(4.0)

In [9]:
b = 11.01
np.floor(b)

np.float64(11.0)

In [10]:
c = 111.99

np.floor(c)

np.float64(111.0)

In [18]:
np.floor(11.5)

np.float64(11.0)

## around()

In [13]:
np.around(11.01) # ceil = 12, floor = 11

np.float64(11.0)

In [14]:
np.around(11.99)

np.float64(12.0)

In [11]:
round(84.98788558, 2)

84.99

In [12]:
np.around(84.98788558, 2)

np.float64(84.99)

In [15]:
np.around(23.802384, 1)

np.float64(23.8)

In [20]:
np.around(11.50)

np.float64(12.0)

## Copy (shallow copy) & Deep copy

### Copy

In [34]:
# when you use copy function, the 2D or 3D array wont get affected like list functions
# Copy will work the same as deep copy

In [27]:
original = np.array([2, 3, 4, 5, 6, 7])
# print(original)

xerox = np.copy(original)
# print(xerox)

xerox[0]=1000

print(original,"------", xerox)

[2 3 4 5 6 7] ------ [1000    3    4    5    6    7]


In [32]:
original = np.array([[2, 3, 4], [5, 6, 7]])
# print(original)

xerox = np.copy(original)
# print(xerox)

xerox[0][0]=10

print(original,"\n\n", xerox)

[[2 3 4]
 [5 6 7]] 

 [[10  3  4]
 [ 5  6  7]]


In [40]:
# Understanding for LIST FUNCTIONS

original = [[2, 3, 4], [5, 6, 7]]
# print(original)

xerox = original.copy()
# print(xerox)

xerox[0][0]=10

print(original,"\n\n", xerox) # not desirable

[[10, 3, 4], [5, 6, 7]] 

 [[10, 3, 4], [5, 6, 7]]


## deepcopy

In [36]:
from copy import deepcopy

In [41]:
original = np.array([[2, 3, 4], [5, 6, 7]])
# print(original)

xerox = deepcopy(original) #deepcopy == np.copy both work the same
# print(xerox)

xerox[0][0]=10

print(original,"\n\n", xerox)

[[2 3 4]
 [5 6 7]] 

 [[10  3  4]
 [ 5  6  7]]


## np.where

In [54]:
arr = np.array([1, 2, 3, 7, 8, 9])
arr

array([1, 2, 3, 7, 8, 9])

In [55]:
np.where(arr==4)

(array([], dtype=int64),)

In [53]:
np.where(arr==3) # it given the index of the element (location)

(array([2]),)

In [44]:
np.where(arr==1)

(array([0]),)

In [45]:
np.where(arr>3)

(array([3, 4, 5]),)

In [46]:
np.where(arr<3)

(array([0, 1]),)

In [49]:
arr = np.array([1, 2, 2, 2, 4, 3, 7, 8, 9])
print(arr)

np.where(arr%2==0)

[1 2 2 2 4 3 7 8 9]


(array([1, 2, 3, 4, 7]),)

In [48]:
np.where(arr%2==1)

(array([0, 2, 3, 5]),)

## Use of np.where to replace the values that does not matches the given condition in array

In [61]:
arr = np.array([1, 2, 2, 2, 4, 3, 7, 8, 9])
print(arr)

np.where(arr%2==1, arr, 88)

[1 2 2 2 4 3 7 8 9]


array([ 1, 88, 88, 88, 88,  3,  7, 88,  9])

In [64]:
arr = np.array([1, 2, 2, 2, 4, 3, 7, 8, 9])
print(arr)

np.where(arr==2, arr, 11)

[1 2 2 2 4 3 7 8 9]


array([11,  2,  2,  2, 11, 11, 11, 11, 11])

In [68]:
arr = np.array([1, 2, 2, 2, 4, 3, 7, 8, 9])
print(arr)

np.where(arr==1, arr, 99) #replace

[1 2 2 2 4 3 7 8 9]


array([ 1, 99, 99, 99, 99, 99, 99, 99, 99])

In [70]:
arr = np.array([1, 2, 2, 2, 4, 3, 7, 8, 9])
print(arr)
np.where(arr%2==1, arr, 77)

[1 2 2 2 4 3 7 8 9]


array([ 1, 77, 77, 77, 77,  3,  7, 77,  9])

## arg

### Argmax --> returns the index of the maximum number in the array

In [71]:
A = [2, 4, 5, 6, 7]

np.argmax(A)

np.int64(4)

In [72]:
x = [324, 54, 55, 33, 11]
np.argmax(x)

np.int64(0)

### argmin --> return the index of minimum number in te array

In [73]:
A = [2, 4, 5, 6, 7]

np.argmin(A)

np.int64(0)

### argsort --> it returns the indexes of the sorted array

In [74]:
x = [324, 54, 55, 33, 11]
np.argsort(x)

# 11, 33, 54, 55, 324

array([4, 3, 1, 2, 0])

### Size --> it will give you the total elements in the array

In [75]:
x = [324, 54, 55, 33, 11]

np.size(x)

5

In [79]:
x = np.array([[324, 54], [55, 33]]) # it works with homogenious array only

np.size(x)

4

## Aggregate Functions

### Min <> Max <> Sum <> Mean <> Mediam <> STD <> Varience <> Mode

- min

In [80]:
X = [2, 3, 4, 1, 7, 5]

np.min(X)

np.int64(1)

- max

In [81]:
X = [2, 3, 4, 1, 7, 5]

np.max(X)

np.int64(7)

- sum

In [82]:
X = [2, 3, 4, 1, 7, 5]

np.sum(X)

np.int64(22)

- Mean

In [84]:
22/6

3.6666666666666665

In [83]:
X = [2, 3, 4, 1, 7, 5] # (a+b+c)/3

np.mean(X)

np.float64(3.6666666666666665)

- mediam

In [86]:
X = [2, 3, 4, 1, 7, 5]

np.median(X)

np.float64(3.5)

- standard deviation

In [87]:
X = [2, 3, 4, 1, 7, 5]

np.std(X)

np.float64(1.9720265943665387)

- variance

In [88]:
X = [2, 3, 4, 1, 7, 5]

np.var(X)

np.float64(3.8888888888888893)

- mode

In [92]:
from statistics import mode

X = [2, 3, 4, 1, 7, 5]

mode(X)

2