## Replacing any item in any array using indexing

In [1]:
import numpy as np

In [5]:
arry = np.array([17, 18, 19, 20, 22]) # mutable --> edit, change anything from an array
arry[1] = 1000
arry

array([  17, 1000,   19,   20,   22])

In [8]:
ary =np.array([1, 2, 3, 4, 5])

ary[3]=9000

In [10]:
ary

array([   1,    2,    3, 9000,    5])

In [23]:
ary =np.array([1, 2, 3, 4, 5])
ary[2] = 4000
ary[-1]=1000
ary

array([   1,    2, 4000,    4, 1000])

In [15]:
ary = np.array([3, 4, 5, 1, 2, 3, 7, 8, 9]).reshape(3, 3)
ary

array([[3, 4, 5],
       [1, 2, 3],
       [7, 8, 9]])

In [16]:
ary #2D

array([[3, 4, 5],
       [1, 2, 3],
       [7, 8, 9]])

In [19]:
# 3==4000

ary[0][0]=4000

In [20]:
ary

array([[4000,    4,    5],
       [   1,    2,    3],
       [   7,    8,    9]])

## Inserting item in array

In [21]:
# insert - wheneven you want to add any specific new item (syntax: np.insert(array, index, value))
# append
# concatinate

In [26]:
ary =np.array([1, 2, 3, 4, 5])

np.insert(ary, 2, 4000)

array([   1,    2, 4000,    3,    4,    5])

In [29]:
np.insert(ary, len(ary), 5000) # wheneven you want to change the very last item. use len(ary)


array([   1,    2,    3,    4,    5, 5000])

In [31]:
np.insert(ary, -1, 456)

array([  1,   2,   3,   4, 456,   5])

In [30]:
len(ary)

5

In [32]:
ary = np.array([3, 4, 5, 1, 2, 3, 7, 8, 9]).reshape(3, 3)
ary #2D

array([[3, 4, 5],
       [1, 2, 3],
       [7, 8, 9]])

In [36]:
ary2 = np.insert(ary, [0][0], 3000)
ary2

array([3000,    3,    4,    5,    1,    2,    3,    7,    8,    9])

In [43]:
ary = np.array([3, 4, 5, 1, 2, 3, 7, 8, 9]).reshape(3, 3)
ary #2D

array([[3, 4, 5],
       [1, 2, 3],
       [7, 8, 9]])

In [41]:
ary[1][1]

np.int64(2)

In [44]:
np.insert(ary, ary[1][1], 123)

array([  3,   4, 123,   5,   1,   2,   3,   7,   8,   9])

In [45]:
ary =np.array([1, 2, 3, 4, 5])
np.insert(ary, 5, 1000)

array([   1,    2,    3,    4,    5, 1000])

## Append

In [46]:
# - it will add new item in the array

In [48]:
array = np.array([4, 5, 6, 7, 8])
array

array([4, 5, 6, 7, 8])

In [49]:
np.append(array, 10)

array([ 4,  5,  6,  7,  8, 10])

In [50]:
np.append(array, (10, 11))

array([ 4,  5,  6,  7,  8, 10, 11])

In [51]:
np.append(array, [12, 13])

array([ 4,  5,  6,  7,  8, 12, 13])

In [52]:
# create an array and all [3, 4, 5] using append function

nums = np.array([1, 2, 3, 4, 5, 6, 7])
np.append(nums, [3, 4, 5])

array([1, 2, 3, 4, 5, 6, 7, 3, 4, 5])

In [53]:
nums = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)

In [54]:
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.append(nums, [3, 4, 5]).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5]])

### appending row wise in matrix

In [ ]:
# - The array must be of same dimensions
# - The array must be of same length

In [57]:
nums = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)

In [62]:
nums #2D

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
nums2 = np.array([[3, 4, 5]])
nums2 #2D

array([[3, 4, 5]])

In [67]:
np.append(nums, nums2, axis=0) #flatten array

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5]])

In [69]:
nums3 = np.array([[2, 3, 4, 5]])
nums3

array([[2, 3, 4, 5]])

In [70]:
np.append(nums, nums3, axis=0) #learning

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

### appending items columns wise in matrix

In [71]:
nums = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
nums2 = np.array([2, 3,]).reshape(2, 1)
nums2

array([[2],
       [3]])

In [74]:
np.append(nums, nums2, axis=1)

array([[1, 2, 3, 2],
       [4, 5, 6, 3]])

In [75]:
num3 = [[66],
        [44]]
num3

[[66], [44]]

In [80]:
cl4 = np.array(num3)
cl4

array([[66],
       [44]])

In [81]:
np.append(nums, cl4, axis=1)

array([[ 1,  2,  3, 66],
       [ 4,  5,  6, 44]])

In [84]:
cl5 = [[23],
        [34],
        [23]]

cl5

[[23], [34], [23]]

In [85]:
np.append(nums, cl5, axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

### Concatenate
- row wise

In [91]:
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
nums2 = np.array([[9, 8, 9]])
nums2

array([[9, 8, 9]])

In [90]:
nums3 = np.array([[2, 3, 4]])
nums3

array([[2, 3, 4]])

In [97]:
np.concatenate([nums, nums2, nums3], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 9],
       [2, 3, 4]])

In [98]:
np.concatenate([nums, nums2, nums3], axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

- column wise

In [99]:
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
cl1 = np.array([[7], [8]])
cl1

array([[7],
       [8]])

In [101]:
cl2 = np.array([[8], [0]])
cl2

array([[8],
       [0]])

In [103]:
np.concatenate([nums, cl1, cl2], axis=1)

array([[1, 2, 3, 7, 8],
       [4, 5, 6, 8, 0]])

In [108]:
# create cl3 ?
cl3 = np.array([[5],[6]])
cl3

# use concatenate function to add one more column
np.concatenate([nums,cl1,cl2,cl3], axis=1)

array([[1, 2, 3, 7, 8, 5],
       [4, 5, 6, 8, 0, 6]])

## Looping on array

In [110]:
list1 = [2, 3, 4, 5, 6]
for i in list1: #for loop & while loop
  print(i)

2
3
4
5
6


In [111]:
aray1  = np.array([2,3, 4, 5, 5, 6 ,6, 7])
aray1

array([2, 3, 4, 5, 5, 6, 6, 7])

In [112]:
for i in aray1:
  print(i)

2
3
4
5
5
6
6
7


In [113]:
array2 = np.array([[2,3, 4, 5, 5,6 ,6, 7]])
array2

array([[2, 3, 4, 5, 5, 6, 6, 7]])

In [114]:
for i in array2:
  print(i)

[2 3 4 5 5 6 6 7]


In [128]:
array2 = np.array([[2,3, 4, 5, 5, 6,6, 7], [23, 34, 45], [44, 55, 66]]) # it wont work in multiple array items
for i in array2:
  print(i)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [123]:
array2 = np.array([2, 3, 4, 5, 5, 6, 6, 7])
array2

array([2, 3, 4, 5, 5, 6, 6, 7])

In [124]:
for i in enumerate(array2):
  print(i)

(0, np.int64(2))
(1, np.int64(3))
(2, np.int64(4))
(3, np.int64(5))
(4, np.int64(5))
(5, np.int64(6))
(6, np.int64(6))
(7, np.int64(7))


In [125]:
for index, value in enumerate(array2):
  print(index, "---", value)

0 --- 2
1 --- 3
2 --- 4
3 --- 5
4 --- 5
5 --- 6
6 --- 6
7 --- 7


### nditer()

In [126]:
array2 = np.array([2, 3, 4, 5, 5, 6, 6, 7]).reshape(4, 2)
array2

array([[2, 3],
       [4, 5],
       [5, 6],
       [6, 7]])

In [127]:
for i in np.nditer(array2):
  print(i)

2
3
4
5
5
6
6
7


In [130]:
for i, v in np.ndenumerate(array2):
  print(i, "---", v)

(0, 0) --- 2
(0, 1) --- 3
(1, 0) --- 4
(1, 1) --- 5
(2, 0) --- 5
(2, 1) --- 6
(3, 0) --- 6
(3, 1) --- 7
