## Numpy --> Numerical Python.

In [ ]:
# it is a base library in python that deals with numbers.
# It is used to perform numerous mathematical operations
# Mathematical ops:
  # Probablity
  # Logarithmic maths
  # statestics
  # Linear Algebra
  # Geometry
  # Trignometry
  # Matrix
  # Random Number Generation

# Numpy is faster than List

# np.Array = collections of homogenous data types (if we have same types of datatype the operations speed increases)
# List = collections of heterogenous data types

In [2]:
import numpy as np
# import numpy

In [ ]:
# converting any list in an array

In [1]:
list1 = [2, 4, 6, 8.0] # heterogenous

print(type(list1))
list1

<class 'list'>


[2, 4, 6, 8.0]

In [3]:
ary = np.array(list1)
ary

array([2., 4., 6., 8.])

In [ ]:
array = np.array([2, '4', 6+0j, 8.6]) # homogenous
array
# type(array)

array(['2', '4', '(6+0j)', '8.6'], dtype='<U64')

In [ ]:
array = np.array([2, 4, 6+0j, 8.6]) # homogenous. (imaginary== Underroot of -1)
array
# type(array)

array([2. +0.j, 4. +0.j, 6. +0.j, 8.6+0.j])

In [ ]:
array = np.array([2, 4, 6, 8.6]) # homogenous
array
# type(array)

array([2. , 4. , 6. , 8.6])

In [ ]:
array = np.array([2, 4, 6, 8]) # homogenous
array
# type(array)

array([2, 4, 6, 8])

In [ ]:
int >> float >> complex >> str

## dtype -

#### Assigning a single data type to an entire array

In [7]:
array = np.array([2, 4, 8.6, 7.0, 8.1], dtype='int') # you can not change any complex number into other datatype except str
array

array([2, 4, 8, 7, 8])

In [9]:
ary = np.array([2, 4, 6.0, 8], dtype='complex')
ary

array([2.+0.j, 4.+0.j, 6.+0.j, 8.+0.j])

In [13]:
# I want convert these numbers in float

numbers = np.array([1, 3, 5, 7, 9], dtype='float')
numbers

# numbers = np.array([1, 3, 5, 7, 9])
# float_numbers = numbers.astype(float)
# float_numbers

array([1., 3., 5., 7., 9.])

In [14]:
# I want convert these numbers in Str
numbers = np.array([1, 3, 5, 7, 9], dtype='str')
numbers

array(['1', '3', '5', '7', '9'], dtype='<U1')

In [18]:
aryy = np.array([2, 3.0, 4.1, "55", 8, 7+0j], dtype='object')
aryy

array([2, 3.0, 4.1, '55', 8, (7+0j)], dtype=object)

In [22]:
# indexing

In [21]:
type(aryy[-1])

complex

In [20]:
type(aryy[3])

str

In [19]:
type(aryy[0])

int

## ndim --> To check the dimensions of an array

In [25]:
# single dimension --> [2, 4, 6, 8]
# double dimension --> [[2, 4, 6, 8],[2, 4, 6, 8]]
# three dimension --> [[[3, 5]]]
# four dimension ---> [[[[2, 3]]]]
# five dimension --> [[[[[2, 3]]]]]

In [ ]:
array = np.array([2, 4, 6, 8])
array

array([2, 4, 6, 8])

In [ ]:
array.ndim

1

In [ ]:
array = np.array([[2, 4, 6, 8],[2, 4, 6, 8]])

array.ndim

2

In [24]:
array = np.array([[[3, 5], [6, 7]]])
array.ndim

3

In [ ]:
ary= np.array([[[2, 3], [5, 6]]])

ary.ndim

3

In [27]:
array=np.array([[[[2, 3]]]])
array.ndim

4

In [28]:
array=np.array([[[[[2, 3]]]]])
array.ndim

5

In [30]:
array = np.array(2.3)
array.ndim

0

## ndmin --> converting lower dimensions array into higher dimensions array

In [32]:
array = np.array(2.3, ndmin=3) # 0D --> 1D ---> 2D ....
print(array)
array.ndim

[[[2.3]]]


3

In [34]:
array = np.array([[[2, 3], [4, 5]]], ndmin=1) # 3D array ---> 1D (we can not reduce higher dimension array into a lower dimension array)
print(array)
array.ndim

[[[2 3]
  [4 5]]]


3

In [38]:
num = np.array([[3, 4], [3, 4]], ndmin=3)
num.ndim
num

array([[[3, 4],
        [3, 4]]])

## Slicing

In [39]:
array = np.array([2, 3, 4, 5])


In [40]:
array[0]

np.int64(2)

In [41]:
array[-1]

np.int64(5)

In [42]:
array[1]

np.int64(3)

In [44]:
num = np.array([[3, 4], [3, 6]]) #[2D]
num

array([[3, 4],
       [3, 6]])

In [45]:
num[0]

array([3, 4])

In [46]:
num[0][1]

np.int64(4)

In [49]:
number = np.array([[3, 4], [5, 9]])

In [51]:
number[1][1]

np.int64(9)

In [52]:
number[1][0]

np.int64(5)

In [54]:
nums = np.array([[2, 1], [9, 0]])
nums[0][1]

np.int64(1)

In [48]:
array = np.array([[[2, 3, 4, 5],
                   [5, 6, 7, 8],
                   [4, 5, 6, 9]],
                  [[5, 6, 7, 8],
                  [9, 9, 8, 9],
                  [2, 3, 4, 6]]])

array.ndim

3

In [56]:
array[1]

array([[5, 6, 7, 8],
       [9, 9, 8, 9],
       [2, 3, 4, 6]])

In [55]:
array[0]

array([[2, 3, 4, 5],
       [5, 6, 7, 8],
       [4, 5, 6, 9]])

In [57]:
array[0][0]

array([2, 3, 4, 5])

In [58]:
array[0][0][2]

np.int64(4)

In [59]:
array = np.array([[[2, 3, 4, 5],
                   [5, 6, 7, 8],
                   [4, 5, 6, 9]],
                  [[5, 6, 7, 8],
                  [9, 9, 8, 9],
                  [2, 3, 4, 6]]])

array.ndim

3

In [60]:
array[1]

array([[5, 6, 7, 8],
       [9, 9, 8, 9],
       [2, 3, 4, 6]])

In [61]:
array[1][1]

array([9, 9, 8, 9])

In [62]:
array[1][1][2]

np.int64(8)

In [63]:
array = np.array([
  [ [1, 2],   [3, 4],   [5, 6],   [7, 8] ],
  [ [9, 10],  [11, 12], [13, 14], [15, 16] ],
  [ [17, 18], [19, 20], [21, 22], [23, 24] ],
  [ [25, 26], [27, 28], [29, 30], [31, 32] ]
])
array.ndim

3

In [64]:
array[1]

array([[ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [65]:
array[1][3]

array([15, 16])

In [68]:
list1 = [3, [4, 5], "babubhai", "raju"]

list1[1][1]

5

In [69]:
complex1 = np.array([
  [ [{"temp": 22.5, "status": "ok"}, {"temp": 21.9, "status": "ok"}],
    [{"temp": 23.0, "status": "warn"}, {"temp": 24.1, "status": "ok"}],
    [{"temp": 19.8, "status": "ok"}, {"temp": 20.0, "status": "fail"}],
    [{"temp": 25.2, "status": "ok"}, {"temp": 26.1, "status": "ok"}] ],

  [ [{"temp": 18.3, "status": "ok"}, {"temp": 19.1, "status": "ok"}],
    [{"temp": 20.5, "status": "warn"}, {"temp": 21.3, "status": "fail"}],
    [{"temp": 22.0, "status": "ok"}, {"temp": 23.2, "status": "ok"}],
    [{"temp": 24.5, "status": "warn"}, {"temp": 25.0, "status": "ok"}] ],

  [ [{"temp": 26.5, "status": "fail"}, {"temp": 27.1, "status": "ok"}],
    [{"temp": 28.0, "status": "ok"}, {"temp": 29.2, "status": "warn"}],
    [{"temp": 30.0, "status": "ok"}, {"temp": 31.1, "status": "fail"}], #(2)(2)(1)
    [{"temp": 32.3, "status": "ok"}, {"temp": 33.5, "status": "ok"}] ],

  [ [{"temp": 34.0, "status": "warn"}, {"temp": 35.2, "status": "fail"}],
    [{"temp": 36.1, "status": "ok"}, {"temp": 37.0, "status": "ok"}],
    [{"temp": 38.4, "status": "warn"}, {"temp": 39.9, "status": "ok"}],
    [{"temp": 40.2, "status": "ok"}, {"temp": 41.5, "status": "fail"}] ]
]
)
complex1.ndim

3

In [70]:
complex1[2][2][1]

{'temp': 31.1, 'status': 'fail'}